### ISSUE TITLE
Problems installing and starting label studio

### ISSUE THREAD

**Issue by ioanachi** [heartexlabs/label-studio-frontend#948]
Hello,
 I tried installing label studio frontend and  I am having some problems starting it. I cloned the repository, did npm install and on npm run start I get this error

"> @heartexlabs/label-studio@1.4.0 start
> yarn run copy-examples && node dev-server.js

yarn run v1.22.19
warning ..\package.json: No license field
$ bash scripts/copy.sh
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command."

I also tried starting label studio 
- in a python virtual environment I did npm install @heartexlabs/label-studio and at " label-studio start" I get the error that it is not installed 
"label-studio: The term 'label-studio' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

Did anyone else have these problems or can tell me what am I doing wrong?

Thank you!

**Comment by makseq** [comment]
Please try to check this video:
https://www.youtube.com/watch?v=QSGgiXie2SE

**Comment by ioanachi** [comment]
Hi @makseq 
Thank you for the suggestion, I tried to follow  the video but It doesn't create the build folder and I get the same error as when I tried to start the project with npm 

>warning "@wojtekmaj/enzyme-adapter-react-17 > enzyme-adapter-utils@1.14.0" has incorrect peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "@wojtekmaj/enzyme-adapter-react-17 > enzyme-adapter-utils > airbnb-prop-types@2.16.0" has incorrect peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > mobx-react@6.3.1" has incorrect peer dependency "react@^16.8.0 || 16.9.0-alpha.0".
warning "mobx-react > mobx-react-lite@2.2.2" has incorrect peer dependency "react@^16.8.0".
warning " > react-sortable-hoc@1.11.0" has unmet peer dependency "prop-types@^15.5.7".
warning " > react-sortable-hoc@1.11.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-sortable-hoc@1.11.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-test-renderer@16.14.0" has incorrect peer dependency "react@^16.14.0".

Using npm I can do the "npm install --legacy-peer-deps" and it installs everything but at npm start I get this error

>yarn run v1.22.19
warning ..\package.json: No license field
$ bash scripts/copy.sh

Thanks!

**Comment by tds-captic** [comment]
I'm running into the same thing with the current master branch: `unable to resolve dependency tree`
I wanted to build a bundle myself, since the NPM package hasn't been updated in over a year and seemingly doesn't work anymore with modern `create-react-app` apps.

@makseq can you direct us to the latest validated commit from which we should be able to build?

**Comment by nicholasrq** [comment]
@ioanachi hi! I assume you're using Windows. unfortunately, the build command was initially designed for Unix systems

you can fix it by following these steps:
- open the `package.json` file and remove the `copy-examples &` part from the `start` command
- copy the `examples/` folder into the `src/` folder. you will see it grayed out because it is ignored by the `.gitignore` file
- run `npm start` or `yarn start` in the root of the LSF folder


should be working now

**Comment by nicholasrq** [comment]
@tds-captic if you're working on Windows, the steps above will work for you as well. you can build from any latest commit in `master`

the npm package is outdated and we're planning to approach the new release strategy soon to ensure such situations never happen

**Comment by tds-captic** [comment]
@nicholasrq great to hear that! Is there a timeline for the release of a newer package?

FYI: I'm running on a macbook M1, and I'm still getting the following dependency errors when trying to build: 
```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @heartexlabs/label-studio@1.4.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || 16.9.0-alpha.0" from mobx-react@6.3.1
npm ERR! node_modules/mobx-react
npm ERR!   dev mobx-react@"^6" from the root project
```

**Comment by nicholasrq** [comment]
@tds-captic speaking of the release strategy, we're planning to finally settle it in Q1'23, probably closer to Q2

regarding your problem, can you please share your 'package.json'?

**Comment by tds-captic** [comment]
Sure! 
I've created a public repo with the full code to test as well: https://github.com/tds-captic/label-studio-in-react-experiment
As far as `package.json` goes, this is the one I get when running: 
```
npx create-react-app@latest FOLDERNAME
npm install @heartexlabs/label-studio
```

```
{
  "name": "label-studio",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@heartexlabs/label-studio": "^1.4.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by tds-captic** [comment]
Turns out I had some version issues in the `package.json` and was able to resolve it basing myself on the following sandbox: https://codesandbox.io/s/label-studio-react-hxiefg?file=/src/index.js

**Comment by nicholasrq** [comment]
@tds-captic oh, that's a shame. thank you for the report, we'll also try to tackle it on our end to ensure the compatibility

for now I'm closing this issue
